repos:
  - repo: https://github.com/terraform-docs/terraform-docs
    rev: 0643382b16ca523deb9c002434df95e825979a45 # v0.21.0
    hooks:
      - id: terraform-docs-go
        args: ["markdown", "table", "--output-file", "README.md", "--output-mode", "inject", "./"]
